// packages/react-native/src/given.ts
import { cleanup, render } from "@testing-library/react-native";
import type { GivenStep } from "@siheom/core";
import type { ReactElement } from "react";
import { setLastRender } from "./query.js";

export async function cleanupReactRoots(): Promise<void> {
  await cleanup();
  setLastRender(null);
}

export const defaultGivens = {
  render: async (element: ReactElement) => {
    const result = await render(element);
    setLastRender(result);
  },
};

export const given = {
  render: (element: ReactElement): GivenStep<typeof defaultGivens> => ({
    given: "render",
    log: "렌더한다",
    args: [element],
  }),
};

// packages/angular/src/given.ts
import { render } from "@testing-library/angular";
import type { GivenStep } from "@siheom/core";
import type { Type } from "@angular/core";

let activeFixture: Awaited<ReturnType<typeof render>>["fixture"] | undefined;

export function detectChanges() {
  activeFixture?.detectChanges();
}

export const defaultGivens = {
  render: async (component: Type<unknown>) => {
    const view = await render(component);
    activeFixture = view.fixture;
  },
};

export const given = {
  render: (component: Type<unknown>): GivenStep<typeof defaultGivens> => ({
    given: "render",
    log: "렌더한다",
    args: [component],
  }),
};
